### ISSUE TITLE
Change smoketest grep parameter

### ISSUE THREAD

**Issue by GarrickHe** [open-switch/opx-test#9]
https://buildkite.com/opx/opx-nas-interface-stretch/builds/15#8974eb25-a758-4066-af54-a52dc0bebc4c/667-856

replace HWADDR with BROADCAST.

**Comment by jeffyin-dell** [comment]
@GarrickHe this is done and can be closed, right?

**Comment by jeffyin-dell** [comment]
Fixed by https://github.com/open-switch/opx-test/commit/075d1d847ed5adedb57dba1219151c452d86dd43
